### ISSUE TITLE
remove some hardcoded values

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/event-sink-consumers#7]
https://github.com/clowder-framework/event-sink-consumers/blob/9349511aeb52e4d0c5b810d4615884892ce1856c/consumers/influxdb/receive_events.py#L18

use client = InfluxDBClient(host='127.0.0.1', port=8086, username='root', password='root', database='dbname')

https://github.com/clowder-framework/event-sink-consumers/blob/main/consumers/influxdb/receive_events.py#L85
use RABBITMQ_URI

**Comment by bodom0015** [comment]
Fixed by #8
